# Generated by Django 3.2.6 on 2021-08-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogmeets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(default='home', max_length=255),
            preserve_default=False,
        ),
    ]
